name: Update Screenshots

on:
  push:
    branches:
      - main

jobs:
  update-screenshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install Puppeteer dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgbm-dev gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libnss3 lsb-release xdg-utils wget

      - name: setwebsite URL
        run: |
          #Replace with you ractual deployed url
           echo "WEBSITE_URL=https://desktop-portfolio-git-main-mcnsgits-projects.vercel.app/" >> $GITHUB_ENV

      - name: Take screenshot
        run: npm run screenshot

      - name: Update README SECTION
        run: npm run update-readme

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "elbow-arson-apron@duck.com"

          git add screenshots/screenshot.png README.md

          # Only commit abd push if there are changes to commit
          if git diff --staged --quiet; then
              echo "No changes to commit."
          else
              git commit -m "Update screenshots [skip ci]"
              git push
          fi
